services:
  db:
    container_name: 'f1-database'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_DB_USER}'
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - f1-network
  app:
    container_name: 'f1-app'
    build: .
    environment:
      - 'SPRING_DATASOURCE_PASSWORD=${POSTGRES_DB_PASSWORD}'
      - 'SPRING_DATASOURCE_USERNAME=${POSTGRES_DB_USER}'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB_NAME}'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - f1-network

networks:
  f1-network:
